### ISSUE TITLE
Provide a short usage example in the README

### ISSUE THREAD

**Issue by danmichaelo** [blackwinter/mediawiki-testwiki#1]
Not being very familiar with the Ruby universe, I simply do not know what to do after `gem install mediawiki-testwiki`…

**Comment by blackwinter** [comment]
Depends on what you're after.
1. If you want to _use_ the Docker images, you don't need the gem; just point Docker at `blackwinter/mediawiki-testwiki` (and possibly a [specific version](https://hub.docker.com/r/blackwinter/mediawiki-testwiki/tags/)) and you're good to go.
2. If you want to _test_ your project against a MediaWiki instance using RSpec (which you probably don't if you're not a Ruby developer), you can use the `RSpecAdapter`; see [mediawiki-gateway](/jpatokal/mediawiki-gateway/blob/27ef552/spec/spec_helper.rb#L24-L32) for an example.
3. If you want to _build_ new Docker images, e.g. for different MediaWiki versions, you can use the Rake tasks provided in the `docker` directory: `rake build VERSION=x.y.z`.

I'll extend the README with those use cases.

**Comment by danmichaelo** [comment]
Thanks!

I was looking for building new images, since I need to do some adjustments to LocalSettings.php like allowing uploads. Now I figured out that I could "cheat" a little by just making my own Docker image on top of yours (using FROM) where I add my own LocalSettings.php file. But it might be a cleaner approach to `rake build VERSION=x.y.z`

**Comment by blackwinter** [comment]
Ok, let me know how it goes or if you need any help getting the build chain running. Besides Docker itself you need to have SQLite (i.e., the program `sqlite3`) and optionally the mechanize gem installed.
